### ISSUE TITLE
How to install babeliumproject/flex-standalone-site on my site

### ISSUE THREAD

**Issue by hafizomair** [babeliumproject/flex-standalone-site#46]
I installed babelium plugin on my moodle site. That plugin is only for one month,Now I want to install "babeliumproject/flex-standalone-site" but I do not have documentation to how to install on my server and link to moodle. So please any one tell me way or give a documentation or tutorials.

**Comment by iperurena** [comment]
We have docs that explain how to deploy all the parts. You'll need [flex-standalone-site](https://github.com/babeliumproject/flex-standalone-site/blob/master/README.md), [the API](https://github.com/babeliumproject/babelium-integration-api/blob/master/README.md) and [the standalone player](https://github.com/babeliumproject/flex-embeddable-player/blob/master/README.md). If you require further assistance, our partners offer premium services and support [here](http://babeliumservices.elurnet.net/).
