### ISSUE TITLE
VideoMerge script append extra non-needed video-seconds

### ISSUE THREAD

**Issue by juananpe** [babeliumproject/flex-standalone-site#9]
An original video of 00:43 (or whatever) can be wrongly extended by VideoMerge script to 01:15.

**Comment by iperurena** [comment]
If the response video is longer that the exercise video, the merging process will take the longest of the two to determine the final duration. You can override this behaviour using ffmpeg as media suite and the option "shortest=1". This way, the final video will be cut-off at the shortest duration.
